version: '3'

services:
  app:
    container_name: crudapi
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mariadb:10.4
    container_name: cruddb
    restart: always
    environment:
      MYSQL_DATABASE: gofiberddbb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: mydbpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql 

volumes:
  mysql:
